version: "3.9"
services:
  mysql-db:
    image: "mysql/mysql-server"
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  frontend:
    image: "phpmyadmin"
    ports:
      - "8080:80"
    environment:
      PMA_HOST : mysql-db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql-db
    links:
      - mysql-db
  bookcatalogueapi:
    build: ../BookCatalogueAPI/
    links:
      - mysql-db:mysql
    ports:
      - "8081:80"
