apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: {{ .Values.common.namespace }}
  labels:
    app: phpmyadmin
spec:
  type: {{ .Values.phpmyadmin.Service.Type }}
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: {{ .Values.common.namespace }}
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: "{{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag }}"
        imagePullPolicy: {{ .Values.phpmyadmin.image.imagePullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: MYSQL_ROOT_PASSWORD
        - name: PMA_HOST
          value: {{ .Values.phpmyadmin.environment.PMA_HOST }}
